# Generated by Django 5.0 on 2024-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theater',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(upload_to='static/movie_imgs'),
        ),
    ]
