# Generated by Django 5.0 on 2024-11-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0002_rename_desciption_theater_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
