# Generated by Django 5.0 on 2024-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0003_alter_bio_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
