# Generated by Django 5.0 on 2024-11-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0004_trailer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash')], max_length=50),
        ),
    ]
