# Generated by Django 5.0 on 2024-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0005_rename_movie_id_order_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
