# Generated by Django 5.0 on 2024-11-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0006_bio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
