# Generated by Django 5.0 on 2024-11-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLand', '0007_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
